### PR TITLE
Rename array functions

### PR DESCRIPTION
**Pull request by cpq**
v7_array_at -> v7_array_get
v7_array_append -> v7_array_push

Added v7_array_set

### CODE REVIEW

**Comment by cpq** [comment]
Hey @mmikulicic , this PR makes array C API more consistent.
Any feedback on it?

**Comment by mmikulicic** [comment]
Hey, yeah sorry I though I mentioned that I wanted to postpone this rename until the humongous regexp PR gets brought into a working shape.

I like the rename, more inline with JS nomenclature. I'll merge it tomorrow.

**Comment by cpq** [comment]
Ah, I thought it got your disapproval.
SGTM, pls let me know when it's a good time to sync/merge it.

**Comment by mmikulicic** [comment]
We can merge this now

**Comment by cpq** [comment]
Synced.
There is one test diff, for Date.toISOString - no idea why it get failing.

**Comment by mmikulicic** [comment]
timezone?

**Comment by cpq** [comment]
Yeah, failed test shows 1 hour difference.

**Comment by mmikulicic** [comment]
we'll fix it later

**Pull request merged**
