### PR TITLE
Squash the last warning when compiling V7

### PR DESCRIPTION
**Pull request by rojer**
[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/471)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Reviewed files:
- src/vm.c @ r1
- v7.c @ r1

---

<sup>**[src/vm.c, line 135 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/471#-JmEj5pxOwmrRQh6QAE7)** ([raw file](https://github.com/cesanta/v7/blob/779fbd0df4716556d05180c181c929bdc1752464/src/vm.c#L135)):</sup>
BTW, `v7_to_pointer` has to be fixed to handle sign extension (e used to have 48-bit wide bitfield but it's not portable). Some platforms (e.g. solaris) have the stack addresses growing from the real top of the address space.

Wouldn't this solve this warning as well: 

```
return (v7_cfunction_t)(uintptr_t) v7_to_pointer(v);
```

?

(This way we only have to care about fixing sign extension in `v7_to_pointer`).

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/471)

**Comment by mmikulicic** [comment]
---

<sup>**[src/vm.c, line 135 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/471#-JmEj5pxOwmrRQh6QAE7)** ([raw file](https://github.com/cesanta/v7/blob/779fbd0df4716556d05180c181c929bdc1752464/src/vm.c#L135)):</sup>
Actually, on a second thought, I think both are wrong.

There might be archs which use 64-bit function pointers and 32 bit "int pointers", i.e. `sizeof(v7_cfunction_t) > sizeof(uintptr_t)`

Is the cast to `(uintptr_t)` really necessary ?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/471)

**Comment by rojer** [comment]
---

<sup>**[src/vm.c, line 135 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/471#-JmEj5pxOwmrRQh6QAE7)** ([raw file](https://github.com/cesanta/v7/blob/779fbd0df4716556d05180c181c929bdc1752464/src/vm.c#L135)):</sup>
ok, how about this?
i'm leaving sign extension change out for now, feel free to follow up.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/471)

**Comment by mmikulicic** [comment]
Reviewed files:
- src/vm.c @ r2
- v7.c @ r2

---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/471)

**Comment by mmikulicic** [comment]
Cool, thanks. Sign extension TODO (not very high prio right now)

---



---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/471)

**Pull request merged**
