### PR TITLE
Sockets: init, ctor, close() and bind()

### PR DESCRIPTION
**Pull request by alashkin**
Hi, @mmikulicic 
In order to keep reasonable size of PR I've created this one with socket basics.
It contain only initialization, ctor, close and bind (bind - as first fucntion)

Please, make review for me.
Pay attention on:
1. Usage of `v7_create_foreign`
2. Creation of "namespaces" constants (Type.SOCK_STREAM) - lines 182-204

Thank you.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/384)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/384)

Reviewed files:
- src/internal.h @ r1
- src/socket.c @ r1
- src/sources.mk @ r1
- src/stdlib.c @ r1
- src/vm.h @ r1
- tests/ecma_report.txt @ r1
- tests/unit_test.c @ r1
- v7.c @ r1

---

What happened to ecma_report.txt ?

---

<sup>**[src/socket.c, line 47 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqP9Mq3mf7Q-Fwy8fK)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L47)):</sup>
Multiline BSD comment style

---

<sup>**[src/socket.c, line 93 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqPbWzAyXnOKWBYHDt)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L93)):</sup>
let's use `val_t` in internal code for consistency. Only user visible API will use `v7_val_t`.

---

<sup>**[src/socket.c, line 105 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqQ3mp_9OwJAPZBe9l)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L105)):</sup>
the static function namespace is shared with all other v7 source files due to amalgamation. Please prefix socket private function with `socket_`.

---

<sup>**[src/socket.c, line 110 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqRHPAOq_NuTBB1nDQ)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L110)):</sup>
minor FYI: `v7_property_value` already does this check and returns V7_UNDEFINED, which when passed to v7_to_foreign returns NULL. The latter is not clearly documented in the v7_to_foreign contract though.

---

<sup>**[src/socket.c, line 121 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqQsgXjBd_2PS8zzZJ)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L121)):</sup>
namespace here as well

---

<sup>**[src/socket.c, line 140 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqS9Sm8yFVgf5SWvdN)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L140)):</sup>
IMHO TYPE_ERROR is more appropriate here. Internal errors are reserved for stuff concerning the interpreter/runtime itself.

---

<sup>**[src/socket.c, line 144 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqW7dXxJc27Zuoe5tW)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L144)):</sup>
Let's document the function's JS signature

---

<sup>**[src/socket.c, line 222 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqUO8UJFw2AC5LDSmY)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L222)):</sup>
Calling WSAStartup must be accompanied by WSACleanup as well.
We should call some kind of `destroy_socket` from v7_destroy.
A TODO comment here would be enough for this round.

---

<sup>**[tests/unit_test.c, line 561 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqVZaOcxPfL0dxegt2)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/tests/unit_test.c#L561)):</sup>
Please use another port name, it's often used on dev machines with something else that was smart enough to use 1234. 

---

<sup>**[v7.c, line 13096 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqSfn5_To9LVglKjjg)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/v7.c#L13096)):</sup>
Do you have plans for allowing to set `local_port` before calling `bind` ?

---

<sup>**[v7.c, line 13165 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqTWzkjy-XSyXvSHAo)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/v7.c#L13165)):</sup>
Being this a library that can be used alongside other code; shouldn't it be the user the one who invokes this?

(I'm assuming that it's not supposed to be called multiple times

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/384)



---

This PR doesn't change it

---

<sup>**[src/socket.c, line 47 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqP9Mq3mf7Q-Fwy8fK)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L47)):</sup>
Hm... Looks like clang-format was here.

---

<sup>**[src/socket.c, line 93 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqPbWzAyXnOKWBYHDt)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L93)):</sup>
Ok

---

<sup>**[src/socket.c, line 105 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqQ3mp_9OwJAPZBe9l)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L105)):</sup>
Ok

---

<sup>**[src/socket.c, line 110 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqRHPAOq_NuTBB1nDQ)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L110)):</sup>
OK

---

<sup>**[src/socket.c, line 121 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqQsgXjBd_2PS8zzZJ)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L121)):</sup>
OK

---

<sup>**[src/socket.c, line 140 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqS9Sm8yFVgf5SWvdN)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L140)):</sup>
OK

---

<sup>**[src/socket.c, line 144 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqW7dXxJc27Zuoe5tW)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L144)):</sup>
Ok

---

<sup>**[src/socket.c, line 222 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqUO8UJFw2AC5LDSmY)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L222)):</sup>
TODO Added

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/384)







---

<sup>**[tests/unit_test.c, line 561 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqVZaOcxPfL0dxegt2)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/tests/unit_test.c#L561)):</sup>
Change to 101112

---

<sup>**[v7.c, line 13096 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqSfn5_To9LVglKjjg)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/v7.c#L13096)):</sup>
Yes. I gonna make property.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/384)







---

<sup>**[v7.c, line 13165 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqTWzkjy-XSyXvSHAo)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/v7.c#L13165)):</sup>
WSAStartup can be called several time, it's not a problem.

---

**Comment by alashkin** [comment]
PLAT

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/384)

Reviewed files:
- src/socket.c @ r2
- tests/unit_test.c @ r2
- v7.c @ r2

---

It looks like the file disappeared in this PR though

---

<sup>**[src/socket.c, line 110 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqRHPAOq_NuTBB1nDQ)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L110)):</sup>
you have to invoke `v7_property_value`

---

<sup>**[v7.c, line 13165 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqTWzkjy-XSyXvSHAo)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/v7.c#L13165)):</sup>
yep as long as WSACleanup is called the exact number of times, otherwise no cleanup is done. ok.

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/384)

Reviewed files:
- tests/ecma_report.txt @ r3





---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/384)



---

Not it exists here, but not in PR on GitHub..? Wtf...

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/384)



---

PTAL

---

<sup>**[src/socket.c, line 111 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqRHPAOq_NuTBB1nDQ)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/src/socket.c#L111)):</sup>
Done.

---

<sup>**[v7.c, line 13171 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/384#-JkqTWzkjy-XSyXvSHAo)** ([raw file](https://github.com/cesanta/v7/blob/82c0fcebed4e49c63bc318c562b0e93654b58f14/v7.c#L13171)):</sup>
Ok.

---

**Comment by alashkin** [comment]
PTAL

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/384)

Reviewed files:
- src/socket.c @ r4
- v7.c @ r4





---

**Pull request merged**
