### PR TITLE
Port old Crypto interface to the new API

### LINKED ISSUE #136: Implement Crypto interface
There is src/crypto.c which uses old internal V7 API. Please port:

- [ ] Port Crypto.md5() and Crypto.md5_hex()
- [ ] Port Crypto.sha1() and Crypto.sha1_hex()

### PR DESCRIPTION
**Pull request by gelraen**
Fixes #136

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/452)

### CODE REVIEW

**Comment by cpq** [comment]
Reviewed files:
- src/crypto.c @ r1
- src/sources.mk @ r1
- src/stdlib.c @ r1
- src/vm.h @ r1
- tests/unit_test.c @ r1
- v7.c @ r1

---

<sup>**[src/sources.mk, line 8 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/452#-JlzemK0Fm_ALpZ1yGCk)** ([raw file](https://github.com/cesanta/v7/blob/e502e39329ff01a5bcd71753a19fe8a4314b0b30/src/sources.mk#L8)):</sup>
I think we can easily ditch OLD_SOURCES at this point

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/452)

**Comment by gelraen** [comment]
---

<sup>**[src/sources.mk, line 8 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/452#-JlzemK0Fm_ALpZ1yGCk)** ([raw file](https://github.com/cesanta/v7/blob/e502e39329ff01a5bcd71753a19fe8a4314b0b30/src/sources.mk#L8)):</sup>
Right, other files are already deleted.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/452)

**Comment by gelraen** [comment]
---

<sup>**[src/sources.mk, line 8 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/452#-JlzemK0Fm_ALpZ1yGCk)** ([raw file](https://github.com/cesanta/v7/blob/e502e39329ff01a5bcd71753a19fe8a4314b0b30/src/sources.mk#L8)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/452)

**Comment by cpq** [comment]
Reviewed files:
- src/sources.mk @ r2

---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/452)

**Pull request merged**
