### PR TITLE
Move non-standard API to smartjs

### PR DESCRIPTION
**Pull request by cpq**
Exported some essential API.
A PR against smartjs that adds that functionality is coming.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/465)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Should we do this after we merged our repos, so that file history can be tracked?
Repo merge will be done with git subtree.

---



---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/465)

**Comment by cpq** [comment]
If you already started on a merge, let's do the merge first.
Otherwise, let's go ahead with this first.

---



---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/465)

**Comment by mmikulicic** [comment]
No didn't start yet. Will do on Tuesday. Today Easter Monday reduced availability.
If we merge now we lose tracked history, but it's not so super important, so let's merge.

---



---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/465)

**Comment by mmikulicic** [comment]
LGTM, please rebase

---

Reviewed files:
- src/array.c @ r1
- src/crypto.c @ r1
- src/internal.h @ r1
- src/interpreter.c @ r1
- src/object.c @ r1
- src/os.c @ r1
- src/socket.c @ r1
- src/sources.mk @ r1
- src/stdlib.c @ r1
- src/vm.c @ r1
- src/vm.h @ r1
- tests/unit_test.c @ r1
- v7.c @ r1
- v7.h @ r1

---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/465)

**Pull request merged**
