### PR TITLE
Fix LLVM symbolizer path

### PR DESCRIPTION
**Pull request by mmikulicic**
[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/434)

### CODE REVIEW

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/434)







---

<sup>**[scripts/platform.mk, line 9 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/434#-JlkDVCB-Qr45WThGR5l)** ([raw file](https://github.com/cesanta/v7/blob/bf8bb81dd34d8f3130ad7ecabe51293d282cb1af/scripts/platform.mk#L9)):</sup>
Don't we need the same for `/llvm-symbolizer` and `clang-tidy`?
I have only `/usr/local/bin/llvm-symbolizer-3.6`, for example

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/434)







---

<sup>**[scripts/platform.mk, line 9 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/434#-JlkDVCB-Qr45WThGR5l)** ([raw file](https://github.com/cesanta/v7/blob/bf8bb81dd34d8f3130ad7ecabe51293d282cb1af/scripts/platform.mk#L9)):</sup>
sure, I was focusing on making it work on docker, because I lost track of whether our workstations are able to run ASAN. Can you?

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/434)







---

<sup>**[scripts/platform.mk, line 9 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/434#-JlkDVCB-Qr45WThGR5l)** ([raw file](https://github.com/cesanta/v7/blob/bf8bb81dd34d8f3130ad7ecabe51293d282cb1af/scripts/platform.mk#L9)):</sup>
No =)
ASAN doesn't work.
I just forget rule #1

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/434)

Reviewed files:
- scripts/platform.mk @ r1





---

**Pull request merged**
