### PR TITLE
correct Str_match(), Str_replace(), Str_search(), Str_split(), Regex_exec()

### PR DESCRIPTION
**Pull request by vrz**
resault ECMA test:
section 15.5 +11 testcases
section 15.10 +209 testcases

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/395)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/395)

Reviewed files:
- Makefile @ r1
- src/internal.h @ r1
- src/regex.c @ r1
- src/string.c @ r1
- src/vm.c @ r1
- src/vm.h @ r1
- tests/Makefile @ r1
- v7.c @ r1
- v7.h @ r1

---

Thanks.

Please let's do the review with reviewable.io.
It detects force pushes and keeps history of previous patchesets along with all the comments.

---

<sup>**[Makefile, line 3 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5bszO-yrpbPYOm1OT)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/Makefile#L3)):</sup>
Why did you disable opts ?

---

<sup>**[src/string.c, line 194 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5c-2-aCgc6Gi5PmE4)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/string.c#L194)):</sup>
wouldn't calling `rx_exec` directly avoid creating the arg array?

---

<sup>**[src/string.c, line 200 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5cdXTflqoyYqxUcfD)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/string.c#L200)):</sup>
since setting properties is expensive, would it be possible to defer this and set it once after the loop?

---

<sup>**[src/string.c, line 240 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5d4IQmpSOTwJswbmu)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/string.c#L240)):</sup>
here as well:

wouldn't calling `rx_exec` directly avoid creating the arg array?

---

<sup>**[src/string.c, line 329 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5d8aPZ2nv3JYcmL4V)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/string.c#L329)):</sup>
and here: wouldn't calling `rx_exec` directly avoid creating the arg array?

---

<sup>**[src/string.c, line 517 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5dB5Sy_8sqLh0AG7G)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/string.c#L517)):</sup>
and here: wouldn't calling `rx_exec` directly avoid creating the arg array?

---

<sup>**[src/vm.c, line 789 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5efFvsRGGacIk0xbF)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/vm.c#L789)):</sup>
good catch

---

<sup>**[src/vm.h, line 74 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5eh6lgYsyrdwWcn6h)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/vm.h#L74)):</sup>
hmm, looks wrong. This is a flag value (e.g. `1 << 0`), not a bit position.
Am I missing something?

---

<sup>**[tests/Makefile, line 4 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5fYXd1yUjtCAZ8GFm)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/tests/Makefile#L4)):</sup>
No need to disable sockets here as well?

---

<sup>**[tests/Makefile, line 5 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5etZRdE9mSSHjsCkX)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/tests/Makefile#L5)):</sup>
also here, why disable optimisations ?

---

**Comment by vrz** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/395)







---

<sup>**[Makefile, line 3 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5bszO-yrpbPYOm1OT)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/Makefile#L3)):</sup>
after enabling O3 with MinGW v7 not work.
i wrote it already in #commits. https://cesanta.slack.com/archives/commits/p1426413107000008

---

<sup>**[src/string.c, line 194 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5c-2-aCgc6Gi5PmE4)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/string.c#L194)):</sup>
yes

---

<sup>**[src/string.c, line 200 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5cdXTflqoyYqxUcfD)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/string.c#L200)):</sup>
it's necessary because lastIndex used in rx_exec()

---

<sup>**[src/vm.h, line 74 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5eh6lgYsyrdwWcn6h)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/vm.h#L74)):</sup>
actually, i don't remember why i set it to 0.
there was some problem...
i'll inform you when found it again

---

<sup>**[tests/Makefile, line 4 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5fYXd1yUjtCAZ8GFm)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/tests/Makefile#L4)):</sup>
i'm not use this makefile, so just forgot it

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/395)







---

<sup>**[Makefile, line 3 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5bszO-yrpbPYOm1OT)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/Makefile#L3)):</sup>
ah that channel wasn't meant for discussing in it.

Are these only warnings or does it fail the tests?

---

<sup>**[src/string.c, line 200 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5cdXTflqoyYqxUcfD)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/string.c#L200)):</sup>
I don't see it, is that about yet uncommited code?

---

**Comment by vrz** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/395)







---

<sup>**[Makefile, line 3 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5bszO-yrpbPYOm1OT)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/Makefile#L3)):</sup>
v7 died.
Assertion failed: n <= (int) sizeof(len), file src/varint.c, line 42

---

<sup>**[src/string.c, line 200 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5cdXTflqoyYqxUcfD)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/string.c#L200)):</sup>
correct rx_exec()

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/395)

Reviewed files:
- src/internal.h @ r2
- src/regex.c @ r2
- src/string.c @ r2
- v7.c @ r2





---

<sup>**[src/string.c, line 200 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5cdXTflqoyYqxUcfD)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/string.c#L200)):</sup>
ah ok I see it's a setter and it's read by `rp->lastIndex`.
Any reason why not just use `v7_to_regexp(ro)->lastIndex = ...` ?

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/395)

Reviewed files:
- src/internal.h @ r3
- src/regex.c @ r3
- src/string.c @ r3
- src/vm.c @ r3
- src/vm.h @ r3
- v7.c @ r3





---

**Comment by vrz** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/395)







---

<sup>**[src/string.c, line 200 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/395#-Jl5cdXTflqoyYqxUcfD)** ([raw file](https://github.com/cesanta/v7/blob/4f2ab9c35aac782a82eafa0218e2444c93517668/src/string.c#L200)):</sup>
agreed

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/395)

Reviewed files:
- src/string.c @ r4
- v7.c @ r4





---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/395)



---

Cool, LGTM.

Please rebase and squash in one single commit so I can merge

---

**Pull request merged**
