### PR TITLE
Fix uninitialized var

### PR DESCRIPTION
**Pull request by mmikulicic**
[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/404)

### CODE REVIEW

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/404)







---

<sup>**[src/vm.c, line 974 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/404#-JlBM1WK46vsVs83q3DZ)** ([raw file](https://github.com/cesanta/v7/blob/cdb239c6c4319b9df0471081f1f84b11f52966df/src/vm.c#L974)):</sup>
How about moving  `if (has != NULL) { *has = 0; }` snippet to the very beginning of the function?

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/404)







---

<sup>**[src/vm.c, line 974 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/404#-JlBM1WK46vsVs83q3DZ)** ([raw file](https://github.com/cesanta/v7/blob/cdb239c6c4319b9df0471081f1f84b11f52966df/src/vm.c#L974)):</sup>
Done.

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/404)



---

PTAL

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/404)

Reviewed files:
- src/vm.c @ r2
- tests/ecma_report.txt @ r1
- v7.c @ r2





---

**Pull request merged**
