### PR TITLE
Implement low level Socket interface

### PR DESCRIPTION
**Pull request by alashkin**
Sorry for PR size. In order to replace exceptions with retvals I had to make a little refactoring and as result PR contains a lot of small changes.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/410)

### CODE REVIEW

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/410)

Reviewed files:
- src/socket.c @ r1
- tests/ecma_report.txt @ r2
- tests/unit_test.c @ r1
- v7.c @ r1





---

<sup>**[src/socket.c, line 69 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/410#-JlExoXiu_t-k10-w0k8)** ([raw file](https://github.com/cesanta/v7/blob/87174c9ed7473cc2a4def365f0e31b660a5f99b8/src/socket.c#L69)):</sup>
I suggest using function instead

---

<sup>**[src/socket.c, line 163 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/410#-JlEy8ptsQqDipo2SLQd)** ([raw file](https://github.com/cesanta/v7/blob/87174c9ed7473cc2a4def365f0e31b660a5f99b8/src/socket.c#L163)):</sup>
add break; here
someone might add a case stmt below, and it'll be fallthrough.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/410)



---

PTAL

---

<sup>**[src/socket.c, line 69 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/410#-JlExoXiu_t-k10-w0k8)** ([raw file](https://github.com/cesanta/v7/blob/87174c9ed7473cc2a4def365f0e31b660a5f99b8/src/socket.c#L69)):</sup>
Actually, I'm too =)

---

<sup>**[src/socket.c, line 163 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/410#-JlEy8ptsQqDipo2SLQd)** ([raw file](https://github.com/cesanta/v7/blob/87174c9ed7473cc2a4def365f0e31b660a5f99b8/src/socket.c#L163)):</sup>
Done.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/410)







---

<sup>**[src/socket.c, line 276 \[r3\]](https://reviewable.io:443/reviews/cesanta/v7/410#-JlF5oui3y09dCV3Lp2T)** ([raw file](https://github.com/cesanta/v7/blob/3d24f7efb79cb44a52adf913631f2a41c3787d77/src/socket.c#L276)):</sup>
clang-format OMG :(

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/410)







---

<sup>**[src/socket.c, line 276 \[r3\]](https://reviewable.io:443/reviews/cesanta/v7/410#-JlF5oui3y09dCV3Lp2T)** ([raw file](https://github.com/cesanta/v7/blob/3d24f7efb79cb44a52adf913631f2a41c3787d77/src/socket.c#L276)):</sup>
you might want to put `sizeof(addr) < 0` in parenthesis, that will push the whole expression in the new line and also makes sense

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/410)







---

<sup>**[src/socket.c, line 69 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/410#-JlExoXiu_t-k10-w0k8)** ([raw file](https://github.com/cesanta/v7/blob/87174c9ed7473cc2a4def365f0e31b660a5f99b8/src/socket.c#L69)):</sup>
Done.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/410)







---

<sup>**[src/socket.c, line 276 \[r3\]](https://reviewable.io:443/reviews/cesanta/v7/410#-JlF5oui3y09dCV3Lp2T)** ([raw file](https://github.com/cesanta/v7/blob/3d24f7efb79cb44a52adf913631f2a41c3787d77/src/socket.c#L276)):</sup>
Cool! It works. Thanks!

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/410)







---

<sup>**[src/socket.c, line 276 \[r3\]](https://reviewable.io:443/reviews/cesanta/v7/410#-JlF5oui3y09dCV3Lp2T)** ([raw file](https://github.com/cesanta/v7/blob/3d24f7efb79cb44a52adf913631f2a41c3787d77/src/socket.c#L276)):</sup>
Done.

---

**Comment by alashkin** [comment]
PLAT

**Comment by cpq** [comment]
LGTM

**Comment by alashkin** [comment]
Was it approve to merge?

**Comment by cpq** [comment]
@mmikulicic pls merge if you're OK with this PR

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/410)

Reviewed files:
- src/socket.c @ r4
- tests/unit_test.c @ r3
- v7.c @ r4





---

<sup>**[src/socket.c, line 375 \[r4\]](https://reviewable.io:443/reviews/cesanta/v7/410#-JlFkWV9rYsNQWhHEg0x)** ([raw file](https://github.com/cesanta/v7/blob/856dff11607f6b99552b0e5cacb1829c51f81f2e/src/socket.c#L375)):</sup>
minor comment:

slight preference for the equivalent `buf_size != 0` which imho resonates better with that difficult to develop 6.5th sense about underflows and signedness.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/410)



---

PTAL

---

<sup>**[src/socket.c, line 375 \[r4\]](https://reviewable.io:443/reviews/cesanta/v7/410#-JlFkWV9rYsNQWhHEg0x)** ([raw file](https://github.com/cesanta/v7/blob/856dff11607f6b99552b0e5cacb1829c51f81f2e/src/socket.c#L375)):</sup>
Done.

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/410)

Reviewed files:
- src/socket.c @ r5
- v7.c @ r5





---

**Pull request merged**
