### PR TITLE
Update v7_main signature

### PR DESCRIPTION
**Pull request by brimstone**
I noticed the signature in the docs didn't match up with the code. I tried to fix this.

### CODE REVIEW

**Comment by mmikulicic** [comment]
Hi! Thanks for helping. Unfortunately that's a generated markdown file. Our script is obviously confused by the fact we have an `)` inside the argument list.

We'll fix the script. Thanks!

**Comment by brimstone** [comment]
Where's the script, want help fixing it?

**Comment by mmikulicic** [comment]
unfortunately it's in a private repo; the script itself is not top secret or anything; but due to technical reasons it would be hard to opensource it;

but what if instead we work around this by also cleaning up the code a little bit:

`void (*pre_freeze_init)(struct v7 *)` -> `v7_init_cb_t pre_freeze_init`

and make a `typedef void (*v7_init_cb_t)(struct v7 *)` ?

What do you think?

**Comment by brimstone** [comment]
I'm just starting to use the project, so I don't really have opinions yet. A callback type is probably fine.

**Pull request closed without merging**
