### PR TITLE
15.9 Date Objects - implementation

### PR DESCRIPTION
**Pull request by alashkin**
Date class is implemented in this pull request.
Should close https://github.com/cesanta/v7/issues/132

### CODE REVIEW

**Comment by mmikulicic** [comment]
Thanks Alexander!

Would it be a problem for you to rebase this against upstream/master instead of having the merge commit?

**Comment by alashkin** [comment]
I supposed no.. but get this on rebase attempt:
>>error: could not apply 7543333... Date: init, ctor & a couple of functions

I'll try to resolve this.
BTW, why don't you like merge commit?

**Comment by alashkin** [comment]
Close on error =)

**Comment by mmikulicic** [comment]
Our workflow is: feature branch, containing one or more commits, which will then get merged into master with a merge commit.

I think merging back the upstream branch (one or more times) often just introduces unnecessarily complicated history. (practical aesthetics? is there such a thing?)

In your example you probably just wanted to check if everything is all right against master. I think that's the job of the continuous integration.

We usually handle merge conflicts by rebasing instead of merging back the master branch. We don't bother rebasing if there are no merge conflicts.

Of course rebasing is not always feasible, especially if there are many commits to rebase, but I found that:

```
[rerere]
        enabled = 1
```

often helps.

Anyway, don't waste much time on it; on a first look it seemed to me that there were not many conflicts, but a merge commit is not a big deal.

**Comment by alashkin** [comment]
Marco, I've successfully rebased, so, I'm going to close this PR and open another one. Is it OK?

**Comment by mmikulicic** [comment]
Sure, it's ok.

Force update is also an option (it would keep the PR, but github will make the existing comments disappear)

**Comment by alashkin** [comment]
I'll open new PR with rebased sources

**Pull request closed without merging**
