### PR TITLE
Small Object.defineProperty enhancement

### PR DESCRIPTION
**Pull request by cpq**
Hi @alashkin , please make a review.
This bumps coverage to 50.94%.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/385)

### CODE REVIEW

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/385)

Reviewed files:
- src/json.c @ r1
- src/vm.c @ r1
- tests/ecma_report.txt @ r1
- v7.c @ r1





---

<sup>**[src/object.c, line 100 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/385#-Jkq9tl9eBpl7wy_uIvd)** ([raw file](https://github.com/cesanta/v7/blob/1ca855db10433f2b791073e2979c7317fe63014f/src/object.c#L100)):</sup>
This line causes another behavior comparing to previous version:
previous one never clear attribute, as new one does.
So, for example, if object already had V7_PROPERTY_DONT_ENUM previous implementation kept it. New one will erase it.
Doesn't it produce any side-effect?

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/385)







---

<sup>**[src/object.c, line 100 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/385#-Jkq9tl9eBpl7wy_uIvd)** ([raw file](https://github.com/cesanta/v7/blob/1ca855db10433f2b791073e2979c7317fe63014f/src/object.c#L100)):</sup>
Yeah, let's see. The previous code was as follows:

    flags = 0;
    if (!v7_is_true(v7, v7_get(v7, desc, "enumerable", 10))) {
       flags |= V7_PROPERTY_DONT_ENUM
    }
    ...
    v7_set_property(,,, flags, val);

`!v7_is_true` is true when the argument is false or undefined. Meaning, if `enumerable` is either false or not specified at all, `DONT_ENUM` is set. Note that the subsequent call will overwrite the attribute:

    Object.defineProperty(o, "x", {enumerable: true});  // no DONT_ENUM 
    Object.defineProperty(o, "x", {});  // sets DONT_ENUM but should not

New code does not do the override.

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/385)







---

<sup>**[src/object.c, line 100 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/385#-Jkq9tl9eBpl7wy_uIvd)** ([raw file](https://github.com/cesanta/v7/blob/1ca855db10433f2b791073e2979c7317fe63014f/src/object.c#L100)):</sup>
> Object.defineProperty(o, "x", {});  // sets DONT_ENUM but should not

enumerable defaults to false, so DONT_ENUM should be set here.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/385)

Reviewed files:
- src/vm.h @ r1





---

<sup>**[src/object.c, line 100 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/385#-Jkq9tl9eBpl7wy_uIvd)** ([raw file](https://github.com/cesanta/v7/blob/1ca855db10433f2b791073e2979c7317fe63014f/src/object.c#L100)):</sup>
Marko, 
Wdym?
That's all is fine or not?

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/385)







---

<sup>**[src/object.c, line 100 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/385#-Jkq9tl9eBpl7wy_uIvd)** ([raw file](https://github.com/cesanta/v7/blob/1ca855db10433f2b791073e2979c7317fe63014f/src/object.c#L100)):</sup>
> Object.defineProperty(o, "x", {});  // sets DONT_ENUM but should not
I parsed it as:  "`defineProperty(o, "x", {})` should not set DON_ENUM" and it caught my eye.

The code itself looks good. Our flags are defined as the exact opposite of the ones in the spec, i.e. an enumerable prop has it's DONT_ENUM flag cleared.

Hence `o_set_attr` will set the flag if the named property is false or missing which is fine since missing "enumerable", "configurable", "writable"  properties default to false.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/385)







---

<sup>**[src/object.c, line 100 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/385#-Jkq9tl9eBpl7wy_uIvd)** ([raw file](https://github.com/cesanta/v7/blob/1ca855db10433f2b791073e2979c7317fe63014f/src/object.c#L100)):</sup>
Ok

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/385)

Reviewed files:
- src/object.c @ r1





---

**Pull request merged**
