### PR TITLE
Add OS.rename and OS.uname methods.

### PR DESCRIPTION
**Pull request by gelraen**
[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/440)

### CODE REVIEW

**Comment by gelraen** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/440)



---

Do I need to put V7_NO_POSIX knob elsewhere? Is there a better name for it?

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/440)



---

No idea on both questions.

---

<sup>**[v7.c, line 14348 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/440#-JlkoGrnJScGSGyqqY1s)** ([raw file](https://github.com/cesanta/v7/blob/96c11ce19ac1e08d182d6ad83ce56151eedd0651/v7.c#L14348)):</sup>
should we fake it when it's not there (e.g. let the user provide some preprocessor macro with the values) ?

---

<sup>**[v7.c, line 14357 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/440#-Jlkod3LXn3cpxdl3g4A)** ([raw file](https://github.com/cesanta/v7/blob/96c11ce19ac1e08d182d6ad83ce56151eedd0651/v7.c#L14357)):</sup>
what are the possible failure modes of`uname`  ?

If they are not common, should't we just throw an exception here?

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/440)

Reviewed files:
- src/internal.h @ r1
- src/os.c @ r1
- tests/unit_test.c @ r1
- v7.c @ r1





---

**Comment by gelraen** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/440)







---

<sup>**[v7.c, line 14348 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/440#-JlkoGrnJScGSGyqqY1s)** ([raw file](https://github.com/cesanta/v7/blob/96c11ce19ac1e08d182d6ad83ce56151eedd0651/v7.c#L14348)):</sup>
Done.

---

<sup>**[v7.c, line 14357 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/440#-Jlkod3LXn3cpxdl3g4A)** ([raw file](https://github.com/cesanta/v7/blob/96c11ce19ac1e08d182d6ad83ce56151eedd0651/v7.c#L14357)):</sup>
I'm not aware of any and http://pubs.opengroup.org/onlinepubs/9699919799/functions/uname.html doesn't tell much about that.

What is the criteria for choosing between returning an error and throwing an exception?

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/440)

Reviewed files:
- src/internal.h @ r2
- src/os.c @ r2
- v7.c @ r2





---

<sup>**[v7.c, line 14357 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/440#-Jlkod3LXn3cpxdl3g4A)** ([raw file](https://github.com/cesanta/v7/blob/96c11ce19ac1e08d182d6ad83ce56151eedd0651/v7.c#L14357)):</sup>
Currently we opted for error values, e.g. in the Socket API, because IO is expected to fail and errors might by recoverable and you're expected to handle it without to much boilerplate and chances for leaking open file descriptors (as we might not want to implement finalizers).

On the other hand, we do use exceptions for all kind of JS runtime errors, and an obscure system error like this might make sense to treat like "hey the runtime is broken, ah btw, it's because of _this_, and _here_".

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/440)

Reviewed files:
- src/internal.h @ r2
- src/os.c @ r2
- tests/unit_test.c @ r1
- v7.c @ r2





---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/440)



---

On non-POSIX systems, I'd rather not have uname() at all. Ditto for rename().

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/440)



---

Is there a better way to have multiplatform JS scripts ?
Shall we, ahem ahem, add support for conditional compilation to JS (in order to reduce the size of the AST as well) ?

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/440)



---

I don't think so.
On embedded, I expect very small & simple JS code, akin to small arduino sketches. On those I'd rather see absent API then stubs, to save space.

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/440)



---

ok, SGTM

---

**Comment by gelraen** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/440)



---

Umm, so it was merged anyway?

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/440)



---

@cpq trigger happy ? :-)

---

**Pull request merged**
