### PR TITLE
Fix ast ne ne

### PR DESCRIPTION
**Pull request by giannitedesco**
Fix the compile. And also fix a typo in evaluation of AST_NE_NE. There's a & where a && is intended.

### CODE REVIEW

**Comment by giannitedesco** [comment]
Hrm, that fix makes some tests fail though, so something else is wrong...

**Comment by mmikulicic** [comment]
Thanks for spotting this!

I only see one diff in `tests/ecma_report.txt`:

```
-9667   FAIL (tail -c +8809565 tests/ecmac.db|head -c 1059): [{"message":"#1.1: e==="invalueof". Actual: e==={"message":"to_json line 5003: ast_fetch_tag(a, &var) == AST_VAR_DECL
+9667   FAIL (tail -c +8809565 tests/ecmac.db|head -c 1059): [{"message":"#1.1: e==="invalueof". Actual: e==={"message":"to_json line 406: ast_fetch_tag(a, &var) == AST_VAR_DECL"
```

which is caused by the fact that a previous commit generated the ecma_report file by running the "amalgamated" `v7.c` (hence the different line numbers).

Do you see other failing tests on your machine?
Or do you mean that some tests that should pass after you fixed this are not passing?

Please keep in mind that the interpreter is still heavily work in progress.

**Comment by mmikulicic** [comment]
BTW C `==` operator yield 0 or 1, so bitwise `&` works as well in this case.

**Comment by giannitedesco** [comment]
Yeah I had to squint hard to see if it changed anything. Depends on precedence and associativity. Ugh :)

I get a diff like this on the ecma tests, but it could be unrelated?
```diff
diff --git a/tests/ecma_report.txt b/tests/ecma_report.txt
index 3d88900..241a8dc 100644
--- a/tests/ecma_report.txt
+++ b/tests/ecma_report.txt
@@ -1281,7 +1281,7 @@
 1277	PASS (tail -c +913922 tests/ecmac.db|head -c 441)
 1278	PASS (tail -c +914364 tests/ecmac.db|head -c 442)
 1279	FAIL (tail -c +914807 tests/ecmac.db|head -c 2996): [{"message":"#5.1: (1 & {toString: function() {return 1}}) === 1. Actual: 0"}]
-1280	PASS (tail -c +917804 tests/ecmac.db|head -c 861)
+1280	FAIL (tail -c +917804 tests/ecmac.db|head -c 861): [{"message":"#1.2: ToInt32(first expression) is called first, and then ToInt32(second expression)"}]
 1281	PASS (tail -c +918666 tests/ecmac.db|head -c 479)
 1282	PASS (tail -c +919146 tests/ecmac.db|head -c 765)
 1283	PASS (tail -c +919912 tests/ecmac.db|head -c 608)
@@ -1304,7 +1304,7 @@
 1300	PASS (tail -c +936212 tests/ecmac.db|head -c 441)
 1301	PASS (tail -c +936654 tests/ecmac.db|head -c 441)
 1302	FAIL (tail -c +937096 tests/ecmac.db|head -c 2994): [{"message":"#5: (1 ^ {toString: function() {return 1}}) === 0. Actual: 1"}]
-1303	PASS (tail -c +940091 tests/ecmac.db|head -c 857)
+1303	FAIL (tail -c +940091 tests/ecmac.db|head -c 857): [{"message":"#1.2: ToInt32(first expression) is called first, and then ToInt32(second expression)"}]
 1304	PASS (tail -c +940949 tests/ecmac.db|head -c 480)
 1305	PASS (tail -c +941430 tests/ecmac.db|head -c 765)
 1306	PASS (tail -c +942196 tests/ecmac.db|head -c 609)
@@ -1327,7 +1327,7 @@
 1323	PASS (tail -c +958507 tests/ecmac.db|head -c 441)
 1324	PASS (tail -c +958949 tests/ecmac.db|head -c 441)
 1325	FAIL (tail -c +959391 tests/ecmac.db|head -c 2994): [{"message":"#5: (0 | {toString: function() {return 1}}) === 1. Actual: 0"}]
-1326	PASS (tail -c +962386 tests/ecmac.db|head -c 857)
+1326	FAIL (tail -c +962386 tests/ecmac.db|head -c 857): [{"message":"#1.2: ToInt32(first expression) is called first, and then ToInt32(second expression)"}]
 1327	PASS (tail -c +963244 tests/ecmac.db|head -c 478)
 1328	PASS (tail -c +963723 tests/ecmac.db|head -c 765)
 1329	PASS (tail -c +964489 tests/ecmac.db|head -c 607)
@@ -1972,7 +1972,7 @@
 1968	PASS (tail -c +1489977 tests/ecmac.db|head -c 439)
 1969	PASS (tail -c +1490417 tests/ecmac.db|head -c 439)
 1970	FAIL (tail -c +1490857 tests/ecmac.db|head -c 2951): [{"message":"#5: 1 * {toString: function() {return 1}} === 1. Actual: NaN"}]
-1971	PASS (tail -c +1493809 tests/ecmac.db|head -c 858)
+1971	FAIL (tail -c +1493809 tests/ecmac.db|head -c 858): [{"message":"#1.2: ToNumber(first expression) is called first, and then ToNumber(second expression)"}]
 1972	PASS (tail -c +1494668 tests/ecmac.db|head -c 464)
 1973	PASS (tail -c +1495133 tests/ecmac.db|head -c 762)
 1974	PASS (tail -c +1495896 tests/ecmac.db|head -c 590)
@@ -2004,7 +2004,7 @@
 2000	PASS (tail -c +1524397 tests/ecmac.db|head -c 439)
 2001	PASS (tail -c +1524837 tests/ecmac.db|head -c 438)
 2002	FAIL (tail -c +1525276 tests/ecmac.db|head -c 2951): [{"message":"#5: 1 / {toString: function() {return 1}} === 1. Actual: NaN"}]
-2003	PASS (tail -c +1528228 tests/ecmac.db|head -c 858)
+2003	FAIL (tail -c +1528228 tests/ecmac.db|head -c 858): [{"message":"#1.2: ToNumber(first expression) is called first, and then ToNumber(second expression)"}]
 2004	PASS (tail -c +1529087 tests/ecmac.db|head -c 464)
 2005	PASS (tail -c +1529552 tests/ecmac.db|head -c 762)
 2006	PASS (tail -c +1530315 tests/ecmac.db|head -c 590)
@@ -2038,7 +2038,7 @@
 2034	PASS (tail -c +1560256 tests/ecmac.db|head -c 439)
 2035	PASS (tail -c +1560696 tests/ecmac.db|head -c 438)
 2036	FAIL (tail -c +1561135 tests/ecmac.db|head -c 2951): [{"message":"#5: 1 % {toString: function() {return 2}} === 1. Actual: NaN"}]
-2037	PASS (tail -c +1564087 tests/ecmac.db|head -c 858)
+2037	FAIL (tail -c +1564087 tests/ecmac.db|head -c 858): [{"message":"#1.2: ToNumber(first expression) is called first, and then ToNumber(second expression)"}]
 2038	PASS (tail -c +1564946 tests/ecmac.db|head -c 464)
 2039	PASS (tail -c +1565411 tests/ecmac.db|head -c 762)
 2040	PASS (tail -c +1566174 tests/ecmac.db|head -c 590)
@@ -2103,7 +2103,7 @@
 2099	PASS (tail -c +1635805 tests/ecmac.db|head -c 438)
 2100	PASS (tail -c +1636244 tests/ecmac.db|head -c 438)
 2101	FAIL (tail -c +1636683 tests/ecmac.db|head -c 2951): [{"message":"#5: 1 - {toString: function() {return 1}} === 0. Actual: NaN"}]
-2102	PASS (tail -c +1639635 tests/ecmac.db|head -c 858)
+2102	FAIL (tail -c +1639635 tests/ecmac.db|head -c 858): [{"message":"#1.2: ToNumber(first expression) is called first, and then ToNumber(second expression)"}]
 2103	PASS (tail -c +1640494 tests/ecmac.db|head -c 466)
 2104	PASS (tail -c +1640961 tests/ecmac.db|head -c 762)
 2105	PASS (tail -c +1641724 tests/ecmac.db|head -c 590)
@@ -2134,7 +2134,7 @@
 2130	PASS (tail -c +1666849 tests/ecmac.db|head -c 443)
 2131	PASS (tail -c +1667293 tests/ecmac.db|head -c 443)
 2132	FAIL (tail -c +1667737 tests/ecmac.db|head -c 2980): [{"message":"#5: 1 << {toString: function() {return 1}} === 2. Actual: 1"}]
-2133	PASS (tail -c +1670718 tests/ecmac.db|head -c 862)
+2133	FAIL (tail -c +1670718 tests/ecmac.db|head -c 862): [{"message":"#1.2: ToNumber(first expression) is called first, and then ToNumber(second expression)"}]
 2134	PASS (tail -c +1671581 tests/ecmac.db|head -c 470)
 2135	PASS (tail -c +1672052 tests/ecmac.db|head -c 766)
 2136	PASS (tail -c +1672819 tests/ecmac.db|head -c 597)
@@ -2163,7 +2163,7 @@
 2159	PASS (tail -c +1915141 tests/ecmac.db|head -c 444)
 2160	PASS (tail -c +1915586 tests/ecmac.db|head -c 444)
 2161	FAIL (tail -c +1916031 tests/ecmac.db|head -c 3020): [{"message":"#5: -4 >> {toString: function() {return 1}} === -2. Actual: -4"}]
-2162	PASS (tail -c +1919052 tests/ecmac.db|head -c 862)
+2162	FAIL (tail -c +1919052 tests/ecmac.db|head -c 862): [{"message":"#1.2: ToNumber(first expression) is called first, and then ToNumber(second expression)"}]
 2163	PASS (tail -c +1919915 tests/ecmac.db|head -c 474)
 2164	PASS (tail -c +1920390 tests/ecmac.db|head -c 766)
 2165	PASS (tail -c +1921157 tests/ecmac.db|head -c 597)
@@ -2192,7 +2192,7 @@
 2188	PASS (tail -c +2153293 tests/ecmac.db|head -c 449)
 2189	PASS (tail -c +2153743 tests/ecmac.db|head -c 449)
 2190	FAIL (tail -c +2154193 tests/ecmac.db|head -c 3072): [{"message":"#5: -4 >>> {toString: function() {return 1}} === 2147483646. Actual: 4.29497e+09"}]
-2191	PASS (tail -c +2157266 tests/ecmac.db|head -c 866)
+2191	FAIL (tail -c +2157266 tests/ecmac.db|head -c 866): [{"message":"#1.2: ToNumber(first expression) is called first, and then ToNumber(second expression)"}]
 2192	PASS (tail -c +2158133 tests/ecmac.db|head -c 496)
 2193	PASS (tail -c +2158630 tests/ecmac.db|head -c 770)
 2194	PASS (tail -c +2159401 tests/ecmac.db|head -c 604)
@@ -9672,7 +9672,7 @@ d-G]/.exec("a") throw SyntaxError. Actual: {"message":"[RegExp] is not defined"}
 9664	FAIL (tail -c +8805291 tests/ecmac.db|head -c 1595): [{"message":"#2: __str = new String(__obj); __str =="tostr". Actual: __str =={}"}]
 9665	FAIL (tail -c +8806887 tests/ecmac.db|head -c 1625): [{"message":"#2: function __obj(){}; __str = new String(__obj); __str =="true". Actual: __str ==[function __obj()]"}]
 9666	FAIL (tail -c +8808513 tests/ecmac.db|head -c 1051): [{"message":"#1.1: e==="intostr". Actual: e==={"message":"#1: var __obj = {toString:function(){throw "intostr"}}; __str = new String(__obj) lead throwing exception"}"}]
-9667	FAIL (tail -c +8809565 tests/ecmac.db|head -c 1059): [{"message":"#1.1: e==="invalueof". Actual: e==={"message":"to_json line 5003: ast_fetch_tag(a, &var) == AST_VAR_DECL"}"}]
+9667	FAIL (tail -c +8809565 tests/ecmac.db|head -c 1059): [{"message":"#1.1: e==="invalueof". Actual: e==={"message":"to_json line 406: ast_fetch_tag(a, &var) == AST_VAR_DECL"}"}]
 9668	FAIL (tail -c +8810625 tests/ecmac.db|head -c 4412): [{"message":"#8: __str =new  String(.00000012345); __str =="1.2345e-7". Actual: __str ==1.2345e-07"}]
 9669	FAIL (tail -c +8815038 tests/ecmac.db|head -c 3557): [{"message":"#4: __str = new String(1.234567890); __str =="1.23456789". Actual: __str ==1.23457"}]
 9670	PASS (tail -c +8818596 tests/ecmac.db|head -c 2571)
@@ -11117,3 +11117,4 @@ d-G]/.exec("a") throw SyntaxError. Actual: {"message":"[RegExp] is not defined"}
 11109	FAIL (tail -c +10101271 tests/ecmac.db|head -c 464): [{"message":"[Date] is not defined"}]
 11110	FAIL (tail -c +10101736 tests/ecmac.db|head -c 568): [{"message":"[Date] is not defined"}]
 11111	FAIL (tail -c +10102305 tests/ecmac.db|head -c 566): [{"message":"[Date] is not defined"}]
+
```

**Comment by mmikulicic** [comment]
Yeah, the other difference is that `&&` is short-cut, but none of that can have practical consequences in this particular line since `==` has higher precedence than both `&` and `&&`, and both sides have no side effect. (The fix should be applied anyway :-) )

Do you get this diff also when running `make run` on the master branch ?
What is your compiler version and build platform?

**Comment by giannitedesco** [comment]
Ah yeah, good point, The test FAILs are in master.

```
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.8.1-10ubuntu9' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.1 (Ubuntu/Linaro 4.8.1-10ubuntu9) 
Linux tyrell 3.11.0-26-generic #45-Ubuntu SMP Tue Jul 15 04:02:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mmikulicic** [comment]
We have a docker image for testing under gcc (my workstation is osx clang), run with `make docker` and indeed it it shows exactly your same diffs.

I should run it more often or even enable ecma diff checks from the CI server (which also runs under linux-gcc). 

Thanks for spotting this!

**Comment by giannitedesco** [comment]
My pleasure. Have a nice day!

**Pull request merged**
