### PR TITLE
Added some AST docs, including the example data breakdown

### PR DESCRIPTION
**Pull request by dimonomid**
While learning how stuff works, I find myself forgetting details quickly, and therefore having to re-examine the same code more than once. So I try to make notes, which I can sometimes convert to something hopefully useful for the newcomers like me.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/514)

### CODE REVIEW

**Comment by mmikulicic** [comment]
awesome thank you!


---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[v7.c, line 6973 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/514#-K1IgqUNwPPgrLpZEW8U)** ([raw file](https://github.com/cesanta/v7/blob/99b908a28da9976405d31b9e686b19ded20ffd88/v7.c#L6973)):</sup>
`s/interpreter/consumer` we also have an (in progress) bytecode compiler


---

<sup>**[v7.c, line 7023 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/514#-K1IhQslNw62HczLaDY4)** ([raw file](https://github.com/cesanta/v7/blob/99b908a28da9976405d31b9e686b19ded20ffd88/v7.c#L7023)):</sup>
`then 0 is stored`


---

<sup>**[v7.c, line 7041 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/514#-K1IhlX0rI72PvQ6Xb8B)** ([raw file](https://github.com/cesanta/v7/blob/99b908a28da9976405d31b9e686b19ded20ffd88/v7.c#L7041)):</sup>
s/script/AST/


---

<sup>**[v7.c, line 7048 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/514#-K1IiURO5S95MrV5qkpz)** ([raw file](https://github.com/cesanta/v7/blob/99b908a28da9976405d31b9e686b19ded20ffd88/v7.c#L7048)):</sup>
perhaps ```
var foo, bar=1;
```

would be more interesting since it shows how a uninitialised vardecl is represented  as well.
<!-- Reviewable comment -K1IiURO5S95MrV5qkq-:-1664563120 -->

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/514)
<!-- Sent from Reviewable.io -->

**Comment by dimonomid** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[v7.c, line 6973 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/514#-K1IgqUNwPPgrLpZEW8U)** ([raw file](https://github.com/cesanta/v7/blob/99b908a28da9976405d31b9e686b19ded20ffd88/v7.c#L6973)):</sup>
Thanks, fixed. By the way, I don't yet have any clear picture about the bytecode compiler, so, the quick question: when we'll switch to bytecode, will the AST still be needed at all? I was thinking of it, and I'm still not sure.


---

<sup>**[v7.c, line 7023 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/514#-K1IhQslNw62HczLaDY4)** ([raw file](https://github.com/cesanta/v7/blob/99b908a28da9976405d31b9e686b19ded20ffd88/v7.c#L7023)):</sup>
You mean, I shouldn't insert the newline? But then, the line will exceed 79 chars (with the dot, it will actually take 81 chars). Should I change my editor's limit from 79 to 81?


---

<sup>**[v7.c, line 7041 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/514#-K1IhlX0rI72PvQ6Xb8B)** ([raw file](https://github.com/cesanta/v7/blob/99b908a28da9976405d31b9e686b19ded20ffd88/v7.c#L7041)):</sup>
Thanks, fixed


---

<sup>**[v7.c, line 7048 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/514#-K1IiURO5S95MrV5qkpz)** ([raw file](https://github.com/cesanta/v7/blob/99b908a28da9976405d31b9e686b19ded20ffd88/v7.c#L7048)):</sup>
Agreed, updated.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/514)

**Comment by mmikulicic** [comment]
LGTM


---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[v7.c, line 6973 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/514#-K1IgqUNwPPgrLpZEW8U)** ([raw file](https://github.com/cesanta/v7/blob/99b908a28da9976405d31b9e686b19ded20ffd88/v7.c#L6973)):</sup>
yes, emitting bytecode from the parser is possible but it couples the parser to the bytecode compilation logic making it harder for us to change any of these steps


---

<sup>**[v7.c, line 7023 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/514#-K1IhQslNw62HczLaDY4)** ([raw file](https://github.com/cesanta/v7/blob/99b908a28da9976405d31b9e686b19ded20ffd88/v7.c#L7023)):</sup>
no I misread the text, for some reason I read "then is 0 stored", don't know if the glitch was in reviewable or in my visual cortex.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/514)

**Comment by mmikulicic** [comment]
merged in 7b82551aa9af3fc21aa008c652702cc91ea5eb64

**Pull request closed without merging**
