### PR TITLE
Change signature of v7_apply to return v7_err

### PR DESCRIPTION
**Pull request by edvakf**
Fixes https://github.com/cesanta/v7/issues/501

This commit introduces a change to the public interface of the library.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/502)

### CODE REVIEW

**Comment by edvakf** [comment]
Test is yet failing because of https://github.com/cesanta/v7/issues/503

**Comment by mmikulicic** [comment]
Could you please rebase against the new master and force push this commit into your branch?

**Comment by edvakf** [comment]
Force pushed.

**Comment by mmikulicic** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[v7.c, line 11585 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/502#-Jy7qNV-qCEZPIiNb4Fr)** ([raw file](https://github.com/cesanta/v7/blob/5a86187a2f805368144b5b0143a408ee4167a521/v7.c#L11585)):</sup>
we have to restore the v7->jmp_buf even when control gets here.
(We don't mind using gotos for this kind of cleanups)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/502)

**Comment by mmikulicic** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[v7.c, line 11585 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/502#-Jy7qNV-qCEZPIiNb4Fr)** ([raw file](https://github.com/cesanta/v7/blob/5a86187a2f805368144b5b0143a408ee4167a521/v7.c#L11585)):</sup>
No problem I'll do it in another PR

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/502)

**Comment by mmikulicic** [comment]
LGTM! Merging

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/502)

**Comment by edvakf** [comment]
OK. To be honest I'm not quite sure how to do it although it looks like it has to be something like 

```
memcpy(&v7->jmp_buf, &saved_jmp_buf, sizeof(saved_jmp_buf));
```

**Comment by mmikulicic** [comment]
Merged in b6a7c87e2dd834409627528e99846063658a266f

Yes, something like that. Actual fix in: fff8bbc5b83d64ab4714ed93f2c6f432ff4e1e4c

Thanks!

**Pull request closed without merging**
