### PR TITLE
Fix #317

### LINKED ISSUE #317: signbit() function leads to compiler issues on Windows using VS2013
`signbit()` function (defined at v7.c file) leads to compiler issues on Windows using VS2013 (Version 12.0.21004.1). The issue is that signbit function is already defined in math.h. 

If you accept pull requests, I could make a fix for that...

### PR DESCRIPTION
**Pull request by cpq**
Hi @alashkin , please make a review

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/400)

### CODE REVIEW

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/400)



---

Should we do the same with `round`? At least MSVC2013 has it.

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/400)



---

Look here: http://blogs.msdn.com/b/vcblog/archive/2013/07/19/c99-library-support-in-visual-studio-2013.aspx

---

**Comment by alashkin** [comment]
..And finally, in 2015 we have C99 implemented in MS compiler. It's miraculous!

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/400)



---

just... wow.

w.r.t. round - made similar change for it.

PTAL

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/400)







---

<sup>**[src/math.c, line 26 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/400#-JlALU4aDnIXcn3_AlpM)** ([raw file](https://github.com/cesanta/v7/blob/ff00edbe83c05e78101f26690a64203726b28df0/src/math.c#L26)):</sup>
May be `_MSC_VER < 1800`?
Accordingly to link I provided only MSVC2013 has it, not MSVC2012.
I don't have MSVC2012 - but i've tried 2013 - it has =)
So, since initial issue was about `signbit` only I'd suggest to change to 1800 here

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/400)







---

<sup>**[src/math.c, line 26 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/400#-JlALU4aDnIXcn3_AlpM)** ([raw file](https://github.com/cesanta/v7/blob/ff00edbe83c05e78101f26690a64203726b28df0/src/math.c#L26)):</sup>
MSDN says 2012 has it:
https://msdn.microsoft.com/en-us/library/hh308342(v=vs.110).aspx

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/400)







---

<sup>**[src/math.c, line 26 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/400#-JlALU4aDnIXcn3_AlpM)** ([raw file](https://github.com/cesanta/v7/blob/ff00edbe83c05e78101f26690a64203726b28df0/src/math.c#L26)):</sup>
This link pointed to `signbit`.
I'm about `round`

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/400)







---

<sup>**[src/math.c, line 26 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/400#-JlALU4aDnIXcn3_AlpM)** ([raw file](https://github.com/cesanta/v7/blob/ff00edbe83c05e78101f26690a64203726b28df0/src/math.c#L26)):</sup>
This: https://msdn.microsoft.com/en-us/library/hh537992(v=vs.110).aspx?

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/400)







---

<sup>**[src/math.c, line 26 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/400#-JlALU4aDnIXcn3_AlpM)** ([raw file](https://github.com/cesanta/v7/blob/ff00edbe83c05e78101f26690a64203726b28df0/src/math.c#L26)):</sup>
You are right, in any case

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/400)

Reviewed files:
- src/interpreter.c @ r1
- src/math.c @ r2





---

**Pull request merged**
