### PR TITLE
Fixed warnings on Linux

### LINKED ISSUE #417: socket warnings
When compiled with gcc on linux:

```
../v7.c: In function 'Socket_connect':
../v7.c: In function 'Socket_connect':
../v7.c:13816:63: warning: comparison is always false due to limited range of data type [-Wtype-limits]
       (port = Socket_get_port(v7, v7_array_get(v7, args, 1))) < 0 ||
                                                               ^
../v7.c: In function 'Socket_sendto':
../v7.c:13872:63: warning: comparison is always false due to limited range of data type [-Wtype-limits]
       (port = Socket_get_port(v7, v7_array_get(v7, args, 1))) < 0 ||
                                                               ^
../v7.c:13816:63: warning: comparison is always false due to limited range of data type [-Wtype-limits]
       (port = Socket_get_port(v7, v7_array_get(v7, args, 1))) < 0 ||
                                                               ^
../v7.c: In function 'Socket_sendto':
../v7.c:13872:63: warning: comparison is always false due to limited range of data type [-Wtype-limits]
       (port = Socket_get_port(v7, v7_array_get(v7, args, 1))) < 0 ||
                                                               ^
../src/socket.c: In function 'Socket_connect':
../src/socket.c:418:63: warning: comparison is always false due to limited range of data type [-Wtype-limits]
       (port = Socket_get_port(v7, v7_array_get(v7, args, 1))) < 0 ||
                                                               ^
../src/socket.c: In function 'Socket_sendto':
../src/socket.c:474:63: warning: comparison is always false due to limited range of data type [-Wtype-limits]
       (port = Socket_get_port(v7, v7_array_get(v7, args, 1))) < 0 ||
                                                               ^
../src/socket.c: In function 'v7_val_t Socket_connect(v7*, val_t, val_t)':
../src/socket.c:418:63: warning: comparison is always false due to limited range of data type [-Wtype-limits]
       (port = Socket_get_port(v7, v7_array_get(v7, args, 1))) < 0 ||
                                                               ^
../src/socket.c: In function 'v7_val_t Socket_sendto(v7*, val_t, val_t)':
../src/socket.c:474:63: warning: comparison is always false due to limited range of data type [-Wtype-limits]
       (port = Socket_get_port(v7, v7_array_get(v7, args, 1))) < 0 ||
```

### PR DESCRIPTION
**Pull request by alashkin**
Hi, @mmikulicic.
Please, review this small PR.

Closes #417

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/420)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/420)

Reviewed files:
- src/socket.c @ r1
- tests/ecma_report.txt @ r1
- v7.c @ r1





---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/420)







---

<sup>**[src/socket.c, line 267 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/420#-JlKYF0uJ4Tj05c3jgFT)** ([raw file](https://github.com/cesanta/v7/blob/bde2f52eccdbba7ca17140587fc5b381dd69ed86/src/socket.c#L267)):</sup>
LGTM merged.

However I'm wondering (and feeling stupid): why did it issue the warning in the first place? Did GCC warn that `int` and `int32_t` are potentially different on some other arch? But why it was always false like if `port` used to be declared as an unsigned type ?

---

**Comment by alashkin** [comment]
There wasn't warning in first place (where `port` was declared as `int`). I just make all port declarations identical.
I have another question: why clang doesn't produce the same warning?

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/420)



---

w.r.t clang: I guess it's a combination of a two opposite things:

- clang is better at understanding your code so it knows when a warning doesn't apply
- clang is younger, hence it didn't have time to collect trillions of warning flags (e.g. gcc's -Wclobbered)

---

**Pull request merged**
