### PR TITLE
Property iteration helper

### PR DESCRIPTION
**Pull request by mmikulicic**
See go.cesanta.com/v7-prop-iter, this implements alternative API 4.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/398)

### CODE REVIEW

**Comment by cpq** [comment]
LGTM modulo minor comments

**Comment by mmikulicic** [comment]
Why not via reviewable?

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/398)



---

PTAL

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/398)

Reviewed files:
- src/vm.c @ r1
- src/vm.h @ r1
- v7.c @ r1





---

**Pull request merged**
