### PR TITLE
Expose v7_compile() to public

### PR DESCRIPTION
**Pull request by cpq**
[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/461)

### CODE REVIEW

**Comment by rojer** [comment]
---

<sup>**[v7.h, line 100 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/461#-Jm2_030psOV7QvzCX8n)** ([raw file](https://github.com/cesanta/v7/blob/709ffbd13ae269961ad10c283aec73d8253666a9/v7.h#L100)):</sup>
a doc would be nice. e.g., what can i do with the output? what is "binary"?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/461)

**Comment by cpq** [comment]
---

<sup>**[v7.h, line 100 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/461#-Jm2_030psOV7QvzCX8n)** ([raw file](https://github.com/cesanta/v7/blob/709ffbd13ae269961ad10c283aec73d8253666a9/v7.h#L100)):</sup>
Doc written.
Also removed v7 param from the arguments.
Also added function v7_main().
Note this is all a preparation to move non-standard JS modules (e.g. file, socket, etc) from V7 repo to Smart.js repo.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/461)

**Comment by rojer** [comment]
---

<sup>**[src/ast.c, line 641 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/461#-Jm3CPUToyr9nrZZXR_8)** ([raw file](https://github.com/cesanta/v7/blob/a59a8a715c4fe776868ce099adc8c908ad99d05d/src/ast.c#L641)):</sup>
if we're following something like Google style guide, then output parameters are supposed to be at the end, so it'd be v7_compile(code, binary, output).

otherwise LG.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/461)

**Comment by cpq** [comment]
---

<sup>**[src/ast.c, line 641 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/461#-Jm3CPUToyr9nrZZXR_8)** ([raw file](https://github.com/cesanta/v7/blob/a59a8a715c4fe776868ce099adc8c908ad99d05d/src/ast.c#L641)):</sup>
Changed arguments order to be inline w/goog style

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/461)

**Comment by rojer** [comment]
LGTM

---



---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/461)

**Pull request merged**
