### PR TITLE
correct 're_match: backtrack overflow!' problem in some ECMA tests

### PR DESCRIPTION
**Pull request by vrz**
[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/424)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/424)







---

<sup>**[src/slre.c, line 1348 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/424#-JlQamYUCIjbSE1OAHeU)** ([raw file](https://github.com/cesanta/v7/blob/95492cd12a10de10bf33fa77fdb861388b0ef993/src/slre.c#L1348)):</sup>
curr_thread is now NULL

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/424)



---

please just git --amend and git push --force. Reviewable will keep history for us

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/424)



---

Could you apply clang-format ? (version 3.6 required)

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/424)

Reviewed files:
- src/slre.c @ r1
- v7.c @ r1





---

**Comment by vrz** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/424)







---

<sup>**[src/slre.c, line 1348 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/424#-JlQamYUCIjbSE1OAHeU)** ([raw file](https://github.com/cesanta/v7/blob/95492cd12a10de10bf33fa77fdb861388b0ef993/src/slre.c#L1348)):</sup>
fixed

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/424)

Reviewed files:
- src/slre.c @ r2
- v7.c @ r2





---

**Pull request merged**
