### PR TITLE
Add assertion on ast_modify_skip and fix tests

### PR DESCRIPTION
**Pull request by edvakf**
Solves this https://github.com/cesanta/v7/issues/497

I'd like a comment because I'm not sure if this is the right way to tackle this case.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/498)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/unit_test.c, line 771 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/498#-JxdfaeMPGCXdv1w-Xbf)** ([raw file](https://github.com/cesanta/v7/blob/897cab9560cb9482491ea1de8c8f0cebb2547025/tests/unit_test.c#L771)):</sup>
good catch!

BTW, this could be done with a smaller change.

Just put `ast_free(&a)` here and undo the other changes.
The mbuf structure is lazily allocated and once reset by ast_free (mbuf_free) it can be used without reinitializing it

(documented in `mbuf_free`: `Free the space allocated for the mbuffer and resets the mbuf structure.`)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/498)

**Comment by edvakf** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/unit_test.c, line 771 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/498#-JxdfaeMPGCXdv1w-Xbf)** ([raw file](https://github.com/cesanta/v7/blob/897cab9560cb9482491ea1de8c8f0cebb2547025/tests/unit_test.c#L771)):</sup>
I see.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/498)

**Comment by mmikulicic** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/498)

**Comment by mmikulicic** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[v7.c, line 6254 \[r2\]](https://reviewable.io:443/reviews/cesanta/v7/498#-Jxdo8uCHhzNVKnPhH-L)** ([raw file](https://github.com/cesanta/v7/blob/8c53b77ade5e3ecd7e3ba8653e4811fe9f24800b/v7.c#L6254)):</sup>
for portability with ansi C we should move this after the declarations

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/498)

**Comment by mmikulicic** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/498)

**Comment by mmikulicic** [comment]
Thanks! merged in 07cfa196d60db523f37f601706b92aa705ca374c

**Pull request closed without merging**
