### PR TITLE
Add comment explaining NaN-packing

### PR DESCRIPTION
**Pull request by cpq**
[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/447)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Reviewed files:
- src/vm.h @ r1
- v7.c @ r1

---

<sup>**[src/vm.h, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYpnjVZ0x4-tK4Ydn)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L26)):</sup>
what is the rightmost 1 bit ?

---

<sup>**[src/vm.h, line 29 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYJsYcYLsA3gw8HRr)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L29)):</sup>
`sign and exponent is 0xfff`
(sign + exponent are 12 bits, while 0xffff is 16 bits.)

---

<sup>**[src/vm.h, line 30 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYiqB_ywozdAqn8mY)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L30)):</sup>
cannot be 0 otherwise can be confused with an Inf (if the rest of the payload is also 0)

---

<sup>**[src/vm.h, line 36 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyZ0J5DBWT7HjXYGK3)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L36)):</sup>
`, provided that they are sign extended`

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Comment by cpq** [comment]
---

<sup>**[src/vm.h, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYpnjVZ0x4-tK4Ydn)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L26)):</sup>
I think if exponent is all-1, and mantissa is all-0, then it's an INFINITY, not NaN

---

<sup>**[src/vm.h, line 29 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYJsYcYLsA3gw8HRr)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L29)):</sup>
Good catch, fixed

---

<sup>**[src/vm.h, line 30 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYiqB_ywozdAqn8mY)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L30)):</sup>
Yeah,  as said earlier

---

<sup>**[src/vm.h, line 36 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyZ0J5DBWT7HjXYGK3)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L36)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Comment by rojer** [comment]
---

<sup>**[src/vm.h, line 36 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyZ0J5DBWT7HjXYGK3)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L36)):</sup>
i'd use "v" to explciitly denote bits used for values and remove "NaN" at the end, since this is no longer a "plain" NaN.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Comment by cpq** [comment]
---

<sup>**[src/vm.h, line 36 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyZ0J5DBWT7HjXYGK3)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L36)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Comment by rojer** [comment]
---

<sup>**[src/vm.h, line 30 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYiqB_ywozdAqn8mY)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L30)):</sup>
earlier where? i don't see it mentioned.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Comment by mmikulicic** [comment]
---

<sup>**[src/vm.h, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYpnjVZ0x4-tK4Ydn)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L26)):</sup>
Yes indeed. I misunderstood what you were showing here. This is a signaling NaN.
As an alternative you could show here a quiet NaN, which has the MSB of the mantissa set and so the LSB can be zero.

This way it's easier to compare this picture with the one below that shows how the tags are encoded. In fact, currently we encode all tags in a way that we avoid generating an Inf value (in order to avoid making sure that the payload is non zero).

---

<sup>**[src/vm.h, line 30 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYiqB_ywozdAqn8mY)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L30)):</sup>
> I think if exponent is all-1, and mantissa is all-0, then it's an INFINITY, not NaN

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Comment by mmikulicic** [comment]
Reviewed files:
- src/vm.h @ r3
- v7.c @ r3

---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Comment by rojer** [comment]
---

<sup>**[src/vm.h, line 30 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYiqB_ywozdAqn8mY)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L30)):</sup>
it'd be helpful to show INF above as well, and mention here that tag cannot be zero to avoid getting an INF.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Comment by cpq** [comment]
---

<sup>**[src/vm.h, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYpnjVZ0x4-tK4Ydn)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L26)):</sup>
Done.

---

<sup>**[src/vm.h, line 30 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYiqB_ywozdAqn8mY)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L30)):</sup>
Done.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Comment by rojer** [comment]
---

<sup>**[src/vm.h, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYpnjVZ0x4-tK4Ydn)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L26)):</sup>
nit: s/and/an/ ?

---

<sup>**[src/vm.h, line 30 \[r4\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlzHHN-vzqJ09A7UV_c)** ([raw file](https://github.com/cesanta/v7/blob/70d4d83205ad6ea669ce71c9e39b3258269612bc/src/vm.h#L30)):</sup>
MSB is 1, sure, but what is this other 1 (bit 48)?

---

<sup>**[src/vm.h, line 34 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYiqB_ywozdAqn8mY)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L34)):</sup>
sorry i don't see tag being non-zero mentioned

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Comment by cpq** [comment]
---

<sup>**[src/vm.h, line 26 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYpnjVZ0x4-tK4Ydn)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L26)):</sup>
Done.

---

<sup>**[src/vm.h, line 30 \[r4\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlzHHN-vzqJ09A7UV_c)** ([raw file](https://github.com/cesanta/v7/blob/70d4d83205ad6ea669ce71c9e39b3258269612bc/src/vm.h#L30)):</sup>
Leftover, removed

---

<sup>**[src/vm.h, line 34 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/447#-JlyYiqB_ywozdAqn8mY)** ([raw file](https://github.com/cesanta/v7/blob/dce25cbfb1b81183ef0de74248bc45ca3c3135bd/src/vm.h#L34)):</sup>
Mentioned about non-zero

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Comment by mmikulicic** [comment]
Reviewed files:
- src/vm.h @ r5
- v7.c @ r5

---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Comment by mmikulicic** [comment]
LGTM

---



---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/447)

**Pull request merged**
