### PR TITLE
Reduce storage size of aux AST table

### PR DESCRIPTION
**Pull request by mmikulicic**
Hi @alashkin, I'd like you to code do this small but noisy code review, thanks.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/430)

### CODE REVIEW

**Comment by alashkin** [comment]
Could it be reviewed with reviewable?

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/430)







---

<sup>**[src/ast.c, line 54 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/430#-JleRm1b9VkHla44LuDe)** ([raw file](https://github.com/cesanta/v7/blob/5161415aa1e4b4b9e2dc972c0a3d86ac0ccb65ae/src/ast.c#L54)):</sup>
I agree with ism about these macroses. 

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/430)

Reviewed files:
- src/ast.h @ r1
- src/interpreter.c @ r1
- src/string.c @ r1
- v7.c @ r1





---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/430)







---

<sup>**[src/ast.c, line 54 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/430#-JleRm1b9VkHla44LuDe)** ([raw file](https://github.com/cesanta/v7/blob/5161415aa1e4b4b9e2dc972c0a3d86ac0ccb65ae/src/ast.c#L54)):</sup>
Done

---

**Comment by alashkin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/430)

Reviewed files:
- src/ast.c @ r2
- v7.c @ r2





---

**Pull request merged**
