### PR TITLE
Handle fread() failure in read_file

### PR DESCRIPTION
**Pull request by rojer**
Squashes a warning.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/450)

### CODE REVIEW

**Comment by mmikulicic** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
Shouldn't it be `< *size`

```
If an error occurs, or the end-of-file is reached, the return value is a short object count (or zero).
```

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by rojer** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
right. but in this case we just did a stat on the file, we know what size to expect.
one can of course argue that if a shorter but valid file is written between stat and read, that should also be allowed...

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by mmikulicic** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
Sure SGTM

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by mmikulicic** [comment]
Reviewed files:
- src/main.c @ r1
- v7.c @ r1

---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by gelraen** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
Does anyone know how `fread` is supposed to behave if `read(2)` fails with `EINTR`?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by mmikulicic** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
AFAIK the f*** functions (no offence intended) handle retries

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by gelraen** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
But, meh, we can think about that once we encounter issues with issuing `fread` only once (which, I suppose, didn't happen yet).

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by gelraen** [comment]
Reviewed files:
- src/main.c @ r1
- v7.c @ r1

---



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by rojer** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
yes, i think the right thing to do actually is to open the file and repeatedly read until EOF, reallocing as needed.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by mmikulicic** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
Actually, after reading around I'm afraid that the fread behaviour w.r.t to eintr is not so well defined

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by mmikulicic** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
do we need to reallocate? We know the file size upfront.
How does fread behave if interrupted when called as `fread(data, size, 1, fp)`, i.e. is it atomic in terms of read items ?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by gelraen** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
C89: `If an error occurs, the resulting value of the file position indicator for the stream is indeterminate.`
Since EINTR is recoverable, I'd asssume that any good stdlib will hide it.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by gelraen** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
I don't think there are any atomicity guarantees for reading stuff from files unless you lock them.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by mmikulicic** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
since fread does buffering, I was wondering whether it will only return an integral number of "items" (here we use n items of 1 byte each)

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Comment by gelraen** [comment]
---

<sup>**[src/main.c, line 33 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/450#-JlzZK-AAFJYYGTV1V0-)** ([raw file](https://github.com/cesanta/v7/blob/8df5b0afc8021acf3a8e28a964be217f1803c230/src/main.c#L33)):</sup>
` If a partial member is read, its value is indeterminate.` http://port70.net/~nsz/c/c89/c89-draft.html#4.9.8.1
Since `size_t` is integral type, it cannot return non-integral number :) But if error/EOF occurs, there's nothing that prohibits it from overwriting a piece of next item in the output buffer.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/450)

**Pull request merged**
