### PR TITLE
Amend, document and test File API

### PR DESCRIPTION
**Pull request by cpq**
File test revealed a problem in `a += b` handler in interpreter: it stringified arguments, which used small buffer, effectively truncating the result.

[Review on Reviewable](https://reviewable.io/reviews/cesanta/v7/397)

### CODE REVIEW

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/397)

Reviewed files:
- docs/api.adoc @ r1
- src/interpreter.c @ r1
- src/stdlib.c @ r1
- tests/ecma_report.txt @ r1
- tests/unit_test.c @ r1
- v7.c @ r1





---

<sup>**[src/stdlib.c, line 200 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/397#-Jl6mX9OAKR0lzAKmEzV)** ([raw file](https://github.com/cesanta/v7/blob/1239380b49763d060770de23cb76352b739a0de1/src/stdlib.c#L200)):</sup>
if write returns -1 because an unrecoverable error this will spin

---

**Comment by cpq** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/397)







---

<sup>**[src/stdlib.c, line 200 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/397#-Jl6mX9OAKR0lzAKmEzV)** ([raw file](https://github.com/cesanta/v7/blob/1239380b49763d060770de23cb76352b739a0de1/src/stdlib.c#L200)):</sup>
I think n would be < 0, and that would break the loop.

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/397)







---

<sup>**[src/stdlib.c, line 200 \[r1\]](https://reviewable.io:443/reviews/cesanta/v7/397#-Jl6mX9OAKR0lzAKmEzV)** ([raw file](https://github.com/cesanta/v7/blob/1239380b49763d060770de23cb76352b739a0de1/src/stdlib.c#L200)):</sup>
ah sorry I misread it

---

**Comment by mmikulicic** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cesanta/v7/397)



---

LGTM, please fix the tests

---

**Pull request merged**
